name: Deploy to GitHub Pages

# This section controls when the workflow runs
on:
  # Triggers the workflow when you push to the main branch
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensures only one deployment happens at a time
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job - prepares your application for deployment
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your code
        uses: actions/checkout@v3
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Configure Pages
        uses: actions/configure-pages@v3
      
      - name: Install project dependencies
        run: npm install
      
      - name: Build the application
        run: npm run build
        env:
          VITE_CLAUDE_API_KEY: ${{ secrets.VITE_CLAUDE_API_KEY }}
      
      - name: Upload the built files
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

  # Deployment job - takes the built files and deploys them
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2